services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: db_energy
      DB_USER: postgres
      DB_PASSWORD: 1303
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      NAME: energy_db
      USER: postgres
      PASSWORD: 1303
      HOST: db
      PORT: 5432

volumes:
  postgres_data: