# Generated by Django 5.2.1 on 2025-05-16 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('verde', 'Verde'), ('amarela', 'Amarela'), ('vermelha1', 'Vermelha - Patamar 1'), ('vermelha2', 'Vermelha - Patamar 2')], max_length=10, unique=True)),
                ('valor_adicional', models.DecimalField(decimal_places=5, max_digits=6)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_consumo', models.CharField(max_length=50)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('potencia_watts', models.FloatField()),
                ('tempo_uso_diario_horas', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_api.ambiente')),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_api.bandeira')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kwh', models.DecimalField(decimal_places=5, max_digits=6)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='energy_api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('consumo_kwh', models.FloatField()),
                ('custo_normal', models.FloatField()),
                ('custo_social', models.FloatField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_api.ambiente')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('data', 'ambiente')},
            },
        ),
    ]
